server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ST-CASTING-DB


movie:
  apiKey: 08cc33bd5ae3a747598ce2ad84376e66
  url-cast: https://api.themoviedb.org/3/movie/