server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    gateway:
      routes:
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web


  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/streaming-ms
          jwk-set-url: ${spring.security.oauth2.jwt.issuer-uri}/protocol/openid-connect/certs

